### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by aladin2000** [andreax79/ServerlessNabaztag#15]
when using command from the web page I get  the error about reco directory. IS it normal ?

192.168.1.ip - - [01/May/2024 19:14:09] code 404, message File not found
192.168.1.ip - - [01/May/2024 19:14:09] "GET /vl/config/reco/fr/Comprend2.mp3 HTTP/1.0" 404 -
192.168.1.ip - - [01/May/2024 19:14:28] code 404, message File not found
192.168.1.ip - - [01/May/2024 19:14:28] "GET /vl/config/reco/fr/Comprend3.mp3 HTTP/1.0" 404 -
192.168.1.ip - - [01/May/2024 19:14:39] code 404, message File not found
192.168.1.ip  - - [01/May/2024 19:14:39] "GET /vl/config/reco/fr/Comprend0.mp3 HTTP/1.0" 404 -

**Comment by andreax79** [comment]
Yes, it is normal. The files are missing.
