### ISSUE TITLE
Bin files explained

### ISSUE THREAD

**Issue by rngtng** [andreax79/ServerlessNabaztag#3]
Hey. First thanks so much for this project, good to see others are working on a custom firmware too. I like your approach very much, being serverless removes a lot of hassle, let's see I may continue to build on top of that and add/merge my changes... let's keep the rabbit alive! 

One (first) question before I get started: what are all those *.bin files?

1. web/vl/bc.jsp - you compiled firmware
2. bootcode.bin - same as web/vl/bc.jsp?
3. conf.bin - ???
4. foo.bin - ???

I find it confusing to have multiple, and delete the unused ones..

btw. my custom nabaztag files is here: https://github.com/rngtng/NabaztagHackKit
I tried to bring some light into the firmware language, addded a little test framework and I just pulled in changes so bytecode can be compiled on mac osx too.

**Comment by andreax79** [comment]
bootcode.bin and web/vl/bc.jsp  are the same file. The compile script (compile.sh) copies bootcode.bin into web/vl/bc.jsp
If I remember, conf.bin is the rabbit configuration (network config, etc..) used by the simulator and foo.bin is an old compiled firmware.

**Comment by rngtng** [comment]
ah thanks for the explanation.. I'll add it to readme later...
